apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-server.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
  selector:
    app: {{ include "wiki-server.name" . }}
